version: "3"
networks:
  clean-api:
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    networks:
      - clean-api
    volumes:
      - ./data:/data/db
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    networks:
      - clean-api
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
#    links:
#      - mongo
